### ISSUE TITLE
Scrollable container not detected

### ISSUE THREAD

**Issue by matthew-dean** [stipsan/compute-scroll-into-view#17]
Not sure which repo you prefer issues on, but I have an issue where I have a horizontal container that's not detected as "scrollable". If I log out all the actions computed by `compute-scroll-into-view`, the container isn't listed. This happens even though the scrollWidth is definitely wider than clientWidth. (I logged to verify.) Is there a way to force computation that a container definitely _is_ scrollable and to set the scroll position?

**Comment by stipsan** [comment]
Interesting, could you make something on codesandbox that reproduces it?

In addition to scrollWidth vs clientWidth it’s also checking if the correct overflow is also checked. 

Are you using scrollMode: “if-needed”?

**Comment by matthew-dean** [comment]
@stipsan I'll try to reduce a test case tomorrow. The container is `overflow: hidden` and I don't have skip overflow hidden enabled. I tried with scrollMode `always` but had no results. The container itself (surrounding the element(s) to be scrolled) def has a scrollWidth larger than clientWidth so I'm as confused as you are. This has worked until now, but all the other scrolling was vertical. This is the first container that I need to scroll horizontally.

**Comment by matthew-dean** [comment]
@stipsan Arg, this morning I couldn't repo with a reduced test case. https://codepen.io/matthewdean/project/editor/ZnVxgz Maybe there's another problem I'm not seeing.

**Comment by matthew-dean** [comment]
@stipsan Ooo! Repro'd! "if-needed" doesn't work if it's a horizontal scroll. -> https://codepen.io/matthewdean/project/editor/ZnVxgz

**Comment by matthew-dean** [comment]
Also not sure why my first `scrollIntoView` doesn't return a promise, which prevents the second scroll.

**Comment by matthew-dean** [comment]
@stipsan Maybe I have an incorrect understanding of "if-needed"? Because I'm finding even in vertical scenarios, there are blocks which, when I call `scrollIntoView` and it's definitely not in view, it doesn't scroll the parent container. I thought if it's not 100% within the block boundaries, it should scroll the parent until it is? (If set to "nearest" for "if-needed" mode.)

**Comment by stipsan** [comment]
Thanks for sharing the repro and the additional info 😄 

> Also not sure why my first scrollIntoView doesn't return a promise, which prevents the second scroll.

Only https://github.com/stipsan/smooth-scroll-into-view-if-needed returns a promise. The reason for this is that there is no way of knowing when a native smooth scrolling has completed. The spec on smooth scrolling is leaving a lot of these details up to the browser vendors: https://drafts.csswg.org/cssom-view/#smooth-scroll-completed

> Maybe I have an incorrect understanding of "if-needed"? Because I'm finding even in vertical scenarios, there are blocks which, when I call scrollIntoView and it's definitely not in view, it doesn't scroll the parent container.


Your understanding is correct, it should always scroll unless the element is 100% visible. 
I forked your repro and it's clearly not detecting `if-needed` as it should: https://codepen.io/stipsan/project/editor/DnVRBL

I'm looking into a fix atm 🙂

**Comment by stipsan** [comment]
The next release should fix your horizontal problems. I could not reproduce a problem with vertical use cases.
Let me know if that's still happening and I'll investigate 😄

**Comment by stipsan** [comment]
Just to keep you posted. I have identified additional edge cases and fixed them in [v1.0.4](https://github.com/stipsan/compute-scroll-into-view/releases/tag/v1.0.4).

These cases are tested by the CI now to protect against regressions in future refactors. I'll keep iterating on the testing suite as there's probably more edge cases that need to be covered.

But before then I'll be working on `smooth-scroll-into-view-if-needed` as it's the last one without a proper automated testing suite on its PRs 😄

**Comment by matthew-dean** [comment]
@stipsan Great, thanks!

**Comment by stipsan** [comment]
Ok thanks for reporting back. Just to make sure I understand correctly: are there two scrolling frames in your use case, where one of them is scrolling correctly but the outermost parent one isn't? 

If so then I know where the culprit is 🙂

**Comment by stipsan** [comment]
I made a repro here: https://codepen.io/stipsan/pen/gjwWXV

It is showing a behavior similar to what you mentioned above 🤔

**Comment by stipsan** [comment]
It looks like `v1.1.17` fixed it: https://codepen.io/stipsan/pen/gjwWXV

**Comment by stipsan** [comment]
Never mind, I found another edge case where it still happens 🤦‍♂️

**Comment by stipsan** [comment]
It only happens when scrolling to `#6` and `#9`. Adding `boundary: document.body` is a temporary fix.
