### ISSUE TITLE
Unable to compile or fetch from unpkg.com

### ISSUE THREAD

**Issue by heruan** [stipsan/compute-scroll-into-view#442]
The unpkg.com link produces a 500 Server Error and compiling hangs at `puppeteer`:

```
$ yarn install
yarn install v1.17.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
[5/5] ⠈ puppeteer
```

**Comment by stipsan** [comment]
Is this still happening? I can access this just fine: https://unpkg.com/compute-scroll-into-view@1.0.11/umd/compute-scroll-into-view.min.js

If it's blocked or something you could try these links:
* https://cdn.jsdelivr.net/npm/compute-scroll-into-view@1.0.11/umd/compute-scroll-into-view.min.js
* https://bundle.run/compute-scroll-into-view@1.0.11

**Comment by heruan** [comment]
It works now!
