### ISSUE TITLE
Incompatible "visualViewport" type with TS 4.0 lib.dom.d.ts

### ISSUE THREAD

**Issue by palci12** [stipsan/compute-scroll-into-view#720]
In new version of Typescript they added visualViewport type and is not compatible with visualViewport type in scroll-into-view package.

> node_modules/typescript/lib/lib.dom.d.ts:18515:14 - error TS2687: All declarations of 'visualViewport' must have identical modifiers.
> 
> 18515     readonly visualViewport: VisualViewport;

**Comment by eaglus** [comment]
@stipsan typings are lost now
look at published directory:
![image](https://user-images.githubusercontent.com/11391682/91991156-3c600300-ed3b-11ea-9e2b-38d45c3b17fb.png)

**Comment by stipsan** [comment]
@eaglus thanks for the report, I unpublished it and will have a look at what's going on
